### ISSUE TITLE
Suggested Icon Support

### ISSUE THREAD

**Issue by AjayChambers** [Crawron/Magpix#8]
> _I'm just gonna give you a general list of icons that I like to have that are sometimes missing from an icon-theme. I find, when I am developing something, public input like this can be very useful. And just FYI, the icon theme looks very impressive so far!_
 + *.cjs 
 + .prettierrc 
 + prettier.config.js
 + .eslintrc.json
 + eslint.config.js
 + .babelrc 
 + babel.config.js
 + .jsbeautifyrc
 + .markdownlintrc

> _A unique icon for '.npmignore' would help so it doesn't look like a package file_
 + .npmignore

> _These two often default to the JSON icon, but it would be very-cool to have a unique icon for these. Separate from the .ts & .js icons. I find my self constantly opening up 'tsconfig.json' when writing TypeScript and I often overlook it because I relay on the visual icons heavily, and as stated above, the current theme I use defaults it to a json icon._

+ jsconfig.json
+ tsconfig.json

>  the three below could just be shown as part of the VSCode config using the same icon as .vscode. When a project has several dev-dependencies, and they all use JSON files for configuration manifests, the JSON icon goes from being very 'visually useful' to a 'visual hindrance' -- that's why I am making a suggestion like this.
+ .vscodeignore
+ settings.json
+ luanch.json

**- Hope the suggestions are useful!**

**Comment by Crawron** [comment]
Icons for `cjs`, `prettier`, `eslint`, `babel`, `npmignore` and `tsconfig` should be supported already. As for the rest of the suggestions, I'll add them to my queue, thanks!
